name: lestari_flutter
description: Animal conservation mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  sizer: ^2.0.15
  permission_handler: any
  intl: ^0.19.0
  loader_overlay: 4.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  dropdown_search: ^5.0.6
  firebase_storage: ^11.5.5
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  model_viewer_plus: ^1.7.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
